# Generated by Django 3.1.7 on 2021-02-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idx')),
                ('user_id', models.CharField(max_length=255, verbose_name='Login_id')),
                ('session_key', models.CharField(max_length=255, verbose_name='session_key')),
                ('ip_address', models.CharField(max_length=20, verbose_name='IP주소')),
                ('login_yn', models.CharField(blank=True, max_length=2, null=True, verbose_name='로그인 여부')),
                ('detail_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='세부사항')),
                ('logout_date', models.DateTimeField(verbose_name='로그아웃 시간')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
            ],
            options={
                'verbose_name_plural': 'session_History',
                'db_table': 'session',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idx')),
                ('user_id', models.CharField(max_length=255, verbose_name='Login_id')),
                ('password', models.CharField(max_length=255, verbose_name='Login_password')),
                ('username', models.CharField(max_length=50, verbose_name='사용자 이름')),
                ('del_yn', models.CharField(default='N', max_length=2, verbose_name='삭제 여부')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='마지막 로그인 시간')),
                ('last_logout', models.DateTimeField(blank=True, null=True, verbose_name='마지막 로그아웃 시간')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='수정 날짜')),
            ],
            options={
                'verbose_name_plural': 'User_Info',
                'db_table': 'user',
                'ordering': ['id'],
            },
        ),
    ]
